"""
Student Engine - Qwen3-0.6B integrated learning system.
Each confirmed concept becomes a Lua module (layer).
Layers can be composed, corrected, or deallocated.
"""

import logging
import json
import os
import sqlite3
import subprocess
import asyncio
import tempfile
import time
from pathlib import Path
from typing import Optional, Dict, List, Tuple

logger = logging.getLogger(__name__)

from backend.ai.tutor_engine import tutor_engine

USE_ADVANCED_MOTOR = True  # Set to False to stick with the "very small AI" vision

BASE_DIR = Path(__file__).parent.parent.parent
MODULES_FILE = BASE_DIR / "backend" / "core_truth" / "modules.json"
DB_FILE = BASE_DIR / "rules.db"
OLLAMA_MODEL_BASE = "qwen3:0.6b"
OLLAMA_URL = "http://localhost:11434/api/generate"

# Mapping of specific subjects to broad experts (MoE)
EXPERT_MAPPING = {
    "logic": "logic",
    "math": "math", "calculus": "math", "differential": "math", "linear": "math", "numerical": "math", "matematica": "math",
    "geometry": "physics", "dynamics": "physics", "energy": "physics", "waves": "physics", 
    "electricity": "physics", "magnetism": "physics", "electromagnetism": "physics",
    "thermodynamics": "physics", "lagrangian": "physics", "hamiltonian": "physics",
    "advanced": "advanced", "special": "advanced", "quantum": "advanced", "cosmology": "advanced", "chaos": "advanced", "frontier": "advanced", "probability": "advanced"
}


def load_modules() -> dict:
    """Load module registry from JSON."""
    if MODULES_FILE.exists():
        return json.loads(MODULES_FILE.read_text())
    return {"modules": {}}


def save_modules(data: dict):
    """Persist module registry."""
    MODULES_FILE.write_text(json.dumps(data, indent=2))


_MODEL_CACHE = {"active": None, "last_check": 0}

async def get_active_model(subject: str = None) -> str:
    """Select the unified MoE model. The actual routing to experts (LoRA adapters) 
    happens internally within the model inference engine."""
    
    # We will use a unified base model that has the MoE architecture built-in
    # or a Multi-LoRA server that dynamically loads adapters.
    target_model = "qwen3-moe:latest"
    
    cache_key = target_model
    now = time.time()
    if _MODEL_CACHE.get(cache_key) and (now - _MODEL_CACHE.get(f"{cache_key}_time", 0) < 300):
        return _MODEL_CACHE[cache_key]

    import httpx
    try:
        async with httpx.AsyncClient(timeout=5) as client:
            resp = await client.get("http://localhost:11434/api/tags")
            if resp.status_code == 200:
                models = [m["name"] for m in resp.json().get("models", [])]
                if target_model in models or target_model.replace(":latest", "") in models:
                    _MODEL_CACHE[cache_key] = target_model
                    _MODEL_CACHE[f"{cache_key}_time"] = now
                    return target_model
    except Exception:
        pass

    # Fallback to the standard base model if MoE is not yet compiled
    return OLLAMA_MODEL_BASE


async def ollama_generate(prompt: str, model: str = None, timeout: int = 120) -> Optional[str]:
    """Call local Qwen3 via Ollama HTTP API (async)."""
    import httpx

    if not model:
        model = await get_active_model()
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.3, "num_predict": 512, "think": False},
    }

    try:
        async with httpx.AsyncClient(timeout=timeout) as client:
            resp = await client.post(OLLAMA_URL, json=payload)
            body = resp.json()
            return body.get("response", "").strip()
    except Exception as e:
        logger.error(f"[Student] Ollama error: {e}")
        return None


class StudentEngine:
    """LLM student that learns by generating and testing Lua code.
    
    Learning flow:
    1. Student receives exercise (generated by teacher)
    2. Student generates Lua code for the concept
    3. Code is tested in sandbox
    4. If test passes → confirmed, module saved as layer
    5. If test fails → student retries with error feedback
    6. After N failures → teacher intervenes
    """

    def __init__(self):
        self.modules = load_modules()
        self.current_level = self._get_next_pending_level()
        self._last_model_used = OLLAMA_MODEL_BASE

    def _get_next_pending_level(self) -> int:
        """Find the next unconfirmed module level."""
        for name, mod in sorted(
            self.modules.get("modules", {}).items(),
            key=lambda x: x[1].get("level", 999),
        ):
            if mod.get("status") == "pending":
                return mod["level"]
        return 999

    def get_module(self, name: str) -> Optional[dict]:
        """Get a module by name."""
        return self.modules.get("modules", {}).get(name)

    def confirm_module(self, name: str, lua_code: str, teacher: str = "owl-alpha", generated_by: str = None):
        """Confirm a module — crystallize it as a permanent layer."""
        mods = self.modules.setdefault("modules", {})
        if name in mods:
            mods[name]["status"] = "confirmed"
            mods[name]["lua_code"] = lua_code
            mods[name]["confirmed_by"] = teacher
            mods[name]["generated_by"] = generated_by or self._last_model_used or OLLAMA_MODEL_BASE
            mods[name]["confirmed_at"] = time.strftime("%Y-%m-%dT%H:%M:%S")
            save_modules(self.modules)
            logger.info(f"[Student] ✅ Module '{name}' confirmed by {teacher}, generated_by={mods[name]['generated_by']}")
            return True
        return False

    def reject_module(self, name: str, reason: str):
        """Reject a module — mark for re-learning."""
        mods = self.modules.setdefault("modules", {})
        if name in mods:
            mods[name]["status"] = "rejected"
            mods[name]["rejection_reason"] = reason
            mods[name]["rejection_count"] = mods[name].get("rejection_count", 0) + 1
            save_modules(self.modules)
            logger.warning(f"[Student] ❌ Module '{name}' rejected: {reason}")

    def deactivate_module(self, name: str):
        """Deactivate a module — free memory, keep for reference."""
        mods = self.modules.setdefault("modules", {})
        if name in mods:
            mods[name]["status"] = "inactive"
            mods[name]["lua_code"] = None  # Free memory
            save_modules(self.modules)
            logger.info(f"[Student] 💤 Module '{name}' deactivated (memory freed)")

    def _get_cognitive_context(self, module: Optional[dict]) -> str:
        """Get the cognitive grounding context based on the current level."""
        if not module:
            return "You are an AI learning and exploring reality through code."
            
        level = module.get("level", 0)
        if level <= 1:
            return "Logical Transformation Layer: You are learning to distinguish differences and count. Use numbers to represent raw states."
        elif level <= 6:
            return "Mathematical Abstraction Layer: You are learning numerical operations and functions. Represent pure logic using math."
        elif level <= 9:
            return "Geometric Representation Layer: You are learning about space, vectors, and time. Represent spatial relationships (x, y, distance)."
        elif level <= 17:
            return "Physical Simulation Layer: You are learning physics and causality. Manipulate forces (vx, vy, acceleration) to affect the 'particle'."
        else:
            return "Advanced Abstraction Layer: You are learning complex systems and theoretical physics. Use advanced mathematics to model the frontier of reality."

    def build_prompt(self, module_name: str, description: str, is_physics: bool = True, hints: list = None) -> str:
        """Construct the official cognitive prompt for a concept."""
        cognitive_context = f"Layer {module_name}"
        
        # Gather dependency code
        deps_code = ""
        module = self.get_module(module_name)
        if module:
            for dep_name in module.get("uses", []):
                dep = self.get_module(dep_name)
                if dep and dep.get("lua_code"):
                    deps_code += f"\n-- {dep_name}:\n{dep['lua_code']}\n"

        hints_str = ""
        if hints:
            hints_str = "\n[CRITICAL HINTS FOR SUCCESS]:\n- " + "\n- ".join(hints) + "\n"

        # Build formula hints based on module type
        formula_hints = ""
        name_lower = module_name.lower()
        desc_lower = description.lower()
        
        if "energy_conservation" in name_lower or ("energy" in name_lower and "conserv" in desc_lower):
            formula_hints = """
[FORMULAS]:
- KE (kinetic energy) = 0.5 * mass * (vx*vx + vy*vy)
- PE (potential energy) = mass * gravity * y
- mass = 2.0, gravity = 9.81
- Total energy = KE + PE (should remain constant)
- Store result in particle.x
"""
        elif "energy_potential" in name_lower or "potential" in name_lower:
            formula_hints = """
[FORMULAS]:
- PE (potential energy) = mass * gravity * height
- mass = 2.0, gravity = 9.81
- height = particle.y
- Store result in particle.x
"""
        elif "energy_kinetic" in name_lower or "kinetic" in name_lower:
            formula_hints = """
[FORMULAS]:
- KE (kinetic energy) = 0.5 * mass * (vx*vx + vy*vy)
- mass = 2.0
- Store result in particle.x
"""
        elif "oscillation" in name_lower or "sine" in desc_lower or "sin(" in desc_lower:
            formula_hints = """
[FORMULAS]:
- position = amplitude * math.sin(2 * math.pi * frequency * time)
- Use math.pi for π
- time can be tracked with a counter variable
- amplitude and frequency are given in the description
"""
        elif "lorentz" in name_lower or "magnetic" in name_lower:
            formula_hints = """
[FORMULAS]:
- Lorentz force: F = q * v * B
- q (charge), v (velocity), B (magnetic field strength)
- Force direction is perpendicular to velocity
- Apply force as acceleration: particle.vx += Fx, particle.vy += Fy
"""
        elif "lagrangian" in name_lower:
            formula_hints = """
[FORMULAS]:
- Lagrangian L = KE - PE
- KE = 0.5 * mass * v^2
- PE = 0.5 * k * x^2 (spring potential)
- mass, k, x are given in the description
"""
        elif "wavefunction" in name_lower or "quantum" in name_lower:
            formula_hints = """
[FORMULAS]:
- Probability density = |psi|^2
- psi is the wavefunction (given in description)
- Use math.sin, math.pi as needed
- Store result in particle.x
"""
        elif "maxwell" in name_lower or "electromagnetic" in name_lower:
            formula_hints = """
[FORMULAS]:
- EM wave: E = amplitude * math.sin(x - c * t)
- c = speed of light (use c=1 for simulation)
- Use math.pi, math.sin as needed
"""

        if is_physics:
            return f"""You are a student at the {cognitive_context}
Your task: write Lua code that implements: {description}

Requirements:
- Must be valid Lua 5.4 code
- The code runs in a sandbox with a 'particle' table (x, y, vx, vy)
- To move the particle, SET particle.vx and particle.vy directly
- For single-frame calculations, write inline code.
- For multi-frame behaviors (like oscillation), wrap your code in 'function update_particle(particle) ... end' so it runs every frame!
- Keep it minimal and correct
- Return ONLY the Lua code, no explanation
{hints_str}{formula_hints}
Available dependencies (previously learned rules):
{deps_code if deps_code else "None"}

Example for 'move right at speed 2':
  particle.vx = 2.0

Write the Lua code:"""
        else:
            return f"""You are a student at the {cognitive_context}
Your task: write a Lua function that implements: {description}

Requirements:
- Must be valid Lua 5.4 code
- Function name: {module_name}(args)
- The function should return a result (number or table) representing the logic
- Keep it minimal and correct
- Return ONLY the Lua code, no explanation
{hints_str}{formula_hints}
Available dependencies:
{deps_code if deps_code else "None"}

Write the Lua code:"""

    async def generate_lua(self, module_name: str, description: str = None, retries: int = 3) -> Optional[str]:
        """Generate Lua code for a module or ad-hoc description."""
        module = self.get_module(module_name)
        
        # Use provided description if module not found
        final_desc = description or (module["description"] if module else None)
        if not final_desc:
            return None

        # Determine if this is a physics module (needs inline code vs function)
        physics_keywords = ["move", "velocity", "acceleration", "force", "bounce",
                           "gravity", "friction", "energy", "wave", "reflect",
                           "ohm", "electric", "magnetic", "field", "quantum", "lagrangian", "mechanics", "slit"]
        is_physics = False
        if module and module.get("subject") in ["physics", "advanced"]:
            is_physics = True
        else:
            is_physics = any(kw in (module_name + final_desc).lower() for kw in physics_keywords)

        # Use Tutor to generate the prompt if advanced motor is enabled
        if USE_ADVANCED_MOTOR:
            prompt = await tutor_engine.get_student_prompt(module_name, {})
        else:
            prompt = self.build_prompt(module_name, final_desc, is_physics)

        for attempt in range(retries):
            logger.info(f"[Student] Generating '{module_name}' (attempt {attempt + 1}/{retries}) [Advanced={USE_ADVANCED_MOTOR}]...")
            
            # Select model dynamically (MoE)
            model = await get_active_model(module.get("subject") if module else None)
            
            if USE_ADVANCED_MOTOR:
                # Use the powerful cascading engine (OpenRouter/Nvidia)
                self._last_model_used = "OpenRouter/Tutor"
                response = await tutor_engine.generate_rule(prompt, {})
            else:
                # Use the selected local expert
                self._last_model_used = model
                response = await ollama_generate(prompt, model=model)

            if response:
                # Extract Lua code from response
                lua_code = self._extract_lua(response)
                if lua_code:
                    return lua_code

            await asyncio.sleep(2)

        return None

    def _extract_lua(self, text: str) -> Optional[str]:
        """Extract clean Lua code from model response.
        Handles markdown code blocks, backticks, and extra text.
        """
        import re

        text = text.strip()

        # Try to extract from markdown code block
        # Match ```lua ... ``` or ``` ... ```
        block_match = re.search(r'```(?:lua)?\s*\n(.*?)```', text, re.DOTALL)
        if block_match:
            return block_match.group(1).strip()

        # Try inline code: `code`
        inline_match = re.search(r'`([^`]+)`', text)
        if inline_match:
            candidate = inline_match.group(1).strip()
            if any(kw in candidate.lower() for kw in ["function", "local", "return"]):
                return candidate

        # Remove any remaining backtick lines
        lines = text.split("\n")
        clean_lines = []
        in_block = False
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("```"):
                in_block = not in_block
                continue
            if not stripped.startswith("`"):
                clean_lines.append(line)

        text = "\n".join(clean_lines).strip()

        # Basic validation
        if len(text) < 5 or len(text) > 2000:
            return None

        # Must contain some Lua keywords
        lua_keywords = ["function", "local", "return", "if", "then", "end", "for", "while"]
        if not any(kw in text.lower() for kw in lua_keywords):
            return None

        return text

    async def learn_module(self, module_name: str, test_fn, teacher_fn=None) -> bool:
        """Full learning cycle for one module (async)."""
        module = self.get_module(module_name)
        if not module:
            print(f"[Student] Module '{module_name}' not found")
            return False

        if module.get("status") == "confirmed":
            print(f"[Student] Module '{module_name}' already confirmed")
            return True

        max_attempts = 5
        for attempt in range(max_attempts):
            # Generate Lua code (async)
            lua_code = await self.generate_lua(module_name)
            if not lua_code:
                logger.warning(f"[Student] Failed to generate code for '{module_name}'")
                continue

            # Test the code
            if asyncio.iscoroutinefunction(test_fn):
                passed, error = await test_fn(lua_code)
            else:
                passed, error = await asyncio.to_thread(test_fn, lua_code)

            if passed:
                self.confirm_module(module_name, lua_code)
                return True
            else:
                logger.warning(f"[Student] Test failed: {error}")
                self.reject_module(module_name, error)

                # If too many failures, ask teacher
                if attempt >= 2 and teacher_fn:
                    logger.info(f"[Student] Asking teacher for help...")
                    teacher_fn(module_name, lua_code, error)

        logger.warning(f"[Student] Failed to learn '{module_name}' after {max_attempts} attempts")
        return False

    def get_confirmed_layers(self) -> list:
        """Get all confirmed modules sorted by level."""
        mods = self.modules.get("modules", {})
        confirmed = [
            (name, mod) for name, mod in mods.items()
            if mod.get("status") == "confirmed"
        ]
        return sorted(confirmed, key=lambda x: x[1].get("level", 999))

    def get_active_lua(self) -> str:
        """Get combined Lua code of all confirmed modules."""
        layers = self.get_confirmed_layers()
        parts = []
        for name, mod in layers:
            code = mod.get("lua_code", "")
            if code:
                parts.append(f"-- Layer {mod['level']}: {name}\n{code}")
        return "\n\n".join(parts)

    def memory_usage(self) -> dict:
        """Report memory usage of the student model."""
        mods = self.modules.get("modules", {})
        confirmed = sum(1 for m in mods.values() if m.get("status") == "confirmed")
        pending = sum(1 for m in mods.values() if m.get("status") == "pending")
        rejected = sum(1 for m in mods.values() if m.get("status") == "rejected")
        inactive = sum(1 for m in mods.values() if m.get("status") == "inactive")

        total_code_size = sum(
            len(m.get("lua_code", "") or "")
            for m in mods.values()
        )

        return {
            "total_modules": len(mods),
            "confirmed": confirmed,
            "pending": pending,
            "rejected": rejected,
            "inactive": inactive,
            "total_code_bytes": total_code_size,
            "ollama_model": _MODEL_CACHE.get("active", OLLAMA_MODEL_BASE),
            "ollama_model_size_mb": 522,
        }


# === Singleton ===
student = StudentEngine()
